apiVersion: v1
kind: ServiceAccount
metadata:
  # The name used in your deployment's spec.serviceAccountName
  name: api-service-account
  namespace: api
  labels:
    # Required for Azure AD Workload Identity
    azure.workload.identity/use: "true"
  annotations:
    # The Client ID of the User-Assigned Managed Identity in Azure
    #azure.workload.identity/client-id: "54c312bf-d611-499b-a91a-7eca2515c8fd"
    azure.workload.identity/client-id: "065f3337-2505-4255-8bca-5ce93d6fc17b"
# Recommended for security: do not mount the default K8s token if your API 
# doesn't need to talk to the Kubernetes API server directly.
automountServiceAccountToken: false
