apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: clspracticecontainerregistry-d0gmgkhtc4g2fcfm.azurecr.io/degreedassessment-web:latest
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_URL
          value: "http://52.149.251.115" # This should match the service name and port of your API service
        - name: ASPNETCORE_URLS
          value: "http://+:8080"  # This forces the app to 8080 and 0.0.0.0
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

