apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
  annotations:
    # Use TCP instead of HTTP for the health check
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "Tcp"
spec:
  type: LoadBalancer # Creates a Public IP for your demo
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 8080