name: Deploy to AKS

on:
  workflow_run:
    workflows: [ "Build and Push to ACR" ]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Required for requesting the OIDC JWT
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Add this line

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}
          resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
          use-kubelogin: 'true' # This enables kubelogin automatically

      - name: List files for debugging
        run: |
          pwd
          ls -R k8s/

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            k8s/BackendApi/service.yaml
            k8s/FrontendWeb/service.yaml
            k8s/BackendApi/service-account.yaml
            k8s/BackendApi/deployment.yaml
            k8s/FrontendWeb/deployment.yaml
            